include: ["_pages"]

title: Geek And Eat Retreat
subtitle: Think. Eat. Repeat.
name: Joe Robertson
email: contact@geekandeat.com

description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Geek & Eat Retreat! A gaming retreat where enthusiasts of board games,
  roleplaying adventures, and video games converge for an unforgettable experience.
  Immerse yourself in epic tabletop battles with classics like Wingspan and innovative
  titles like Gloomhaven, dive into collaborative storytelling through Dungeons & Dragons
  and Shadowrun sessions, and enjoy in-your-face action with local video game with both console
  and arcade classics. Our retreat offers themed rooms and includes meals inspired by geek culture.
  Whether you're a seasoned gamer or a curious newcomer, join us for camaraderie, strategy, and
  endless fun in a judgment-free zone dedicated to all things geeky. Book your spot today and
  level up your gaming life!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.geekandeat.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed

##### Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      show_date: true

##### Theme config
locale: "en-US"
logo: "/assets/images/logo.jpeg"
# "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "neon"
teaser: /assets/images/teaser.jpeg

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
